# Streamlit Secrets Configuration
# Place this file in .streamlit/secrets.toml in your project directory

# Your HeyGen API Key
heygen_api_key = "YOUR_HEYGEN_API_KEY_HERE"

# Optional: Additional configuration can be added here
# debug_mode = false
# session_timeout = 45
